export const Flims = [
  {
    id: "1",
    name: "Parasite",
    rate: 8,
    type: "Drama, Thriller",
    img: "assets/flim-kr/parasite.jpg",
    info: "Greed and class discrimination threaten the newly formed symbiotic relationship between the wealthy Park family and the destitute Kim clan.",
  },
  {
    id: "2",
    name: "Silienced",
    rate: 8,
    type: "Drama",
    img: "assets/flim-kr/silienced.jpg",
    info: "Based on real events, this film depicts the story of a school for the hearing-impaired where young deaf students were sexually assaulted by the faculty members over a long period of time.",
  },
  {
    id: "3",
    name: "A Taxi Driver",
    rate: 7.9,
    type: "Action, Drama, History",
    img: "assets/flim-kr/a-taxi-driver.jpg",
    info: "A widowed father and taxi driver who drives a German reporter from Seoul to Gwangju to cover the 1980 uprising, soon finds himself regretting his decision after being caught in the violence around him.",
  },
  {
    id: "4",
    name: "1987",
    rate: 7.8,
    type: "Drama, History, Thriller",
    img: "assets/flim-kr/OIP.jpg",
    info: "In 1987 Korea under an oppressive military regime, the unlawful interrogation and death of a college student ignite ordinary citizens to fight for the truth and bring about justice.",
  },
  {
    id: "5",
    name: "Miracle in Cell No. 7",
    rate: 8.2,
    type: "Drama",
    img: "assets/flim-kr/MRC.jpg",
    info: "A story of love between a mentally-ill father who was wrongly accused of murder and his lovely six year old daughter. Prison will be their home.",
  },
  {
    id: "6",
    name: "The Host",
    rate: 7.1,
    type: "Drama, Horror, Sci-Fi",
    img: "assets/flim-kr/OIPI.jpg",
    info: "A monster emerges from Seoul's Han River and begins attacking people. One victim's loving family does what it can to rescue her from its clutches.",
  },
  {
    id: "7",
    name: "The Wailing",
    rate: 7.4,
    type: "Drama, Horror, Sci-Fi",
    img: "assets/flim-kr/OIPII.jpg",
    info: "Soon after a stranger arrives in a little village, a mysterious sickness starts spreading. A policeman, drawn into the incident, is forced to solve the mystery in order to save his daughter.",
  },
  {
    id: "8",
    name: "Peninsula",
    rate: 5.5,
    type: "Drama, Horror, Sci-Fi",
    img: "assets/flim-kr/R.jpg",
    info: "A zombie virus has in the last 4 years spread to all South Korea. 4 Koreans in Hong Kong sail through the blockade to Incheon for USD20,000,000 on a truck.",
  },
  {
    id: "9",
    name: "Extreme Job",
    rate: 10,
    type: "Drama, Horror, Sci-Fi",
    img: "assets/flim-kr/OIPR.jpg",
    info: "A police undercover operation takes a delicious, unexpected turn.",
  }
]
